web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: '192.168.1.34'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://192.168.1.34'
      gitlab_rails['gitlab_shell_ssh_port'] = 2202
      gitlab_rails['time_zone'] = 'Asia/Shanghai'
  ports:
    - '80:80'
    - '2202:22'
  volumes:
    - '/data/gitlab/config:/etc/gitlab'
    - '/data/gitlab/logs:/var/log/gitlab'
    - '/data/gitlab/data:/var/opt/gitlab'